name: Build and publish custom ERPNext image

on:
  push:
    branches: ["release"]
    tags:
      - "v*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Validate and encode custom_apps.json
        run: |
          if ! jq empty custom_apps.json; then
            echo "custom_apps.json is not valid JSON!"
            exit 1
          fi
          APPS_JSON_BASE64=$(base64 -w 0 custom_apps.json)
          echo "APPS_JSON_BASE64=$APPS_JSON_BASE64" >> "$GITHUB_ENV"

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            FRAPPE_PATH=https://github.com/frappe/frappe
            FRAPPE_BUILD=v15.98.1
            FRAPPE_BRANCH=v15.100.1
            APPS_JSON_BASE64=${{ env.APPS_JSON_BASE64 }}
          file: ./images/layered/Containerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
